### ISSUE TITLE
YuqueCli is not supported for multiworkspaces

### ISSUE THREAD

**Issue by jeffizz** [lengmoXXL/vscode-yuque-cli#1]
YuqueCli is not work in multiworkspaces environment

**Comment by lengmoXXL** [comment]
Yes, it simply assert that it's single workspace. It's behaviors in multiworkspaces need to be designed. This may be considered in the next update. Thank you very much!

**Comment by jeffizz** [comment]
期待新的版本

**Comment by lengmoXXL** [comment]
supported in 0.3.0
